# Generated by Django 2.2.1 on 2019-07-29 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/', verbose_name='画像ファイル')),
                ('text_tag', models.CharField(max_length=50, verbose_name='テキストタグ')),
                ('effect_tag', models.CharField(max_length=50, null=True, verbose_name='エフェクトタグ')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 7, 30, 8, 48, 13, 617610), verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 7, 30, 8, 48, 13, 617610), verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.FileField(upload_to='movie/', verbose_name='動画ファイル')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 7, 30, 8, 48, 13, 649555), verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 7, 30, 8, 48, 13, 649555), verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.FileField(upload_to='music/', verbose_name='音楽ファイル')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 7, 30, 8, 48, 13, 649555), verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 7, 30, 8, 48, 13, 649555), verbose_name='更新日時')),
            ],
        ),
    ]
