# Generated by Django 2.2.1 on 2019-07-30 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 18, 23, 50, 434597), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='image',
            name='effect_tag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='エフェクトタグ'),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 18, 23, 50, 434597), verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 18, 23, 50, 499424), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 18, 23, 50, 499424), verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='music',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 18, 23, 50, 498427), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='music',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 18, 23, 50, 498427), verbose_name='更新日時'),
        ),
    ]
