# Generated by Django 2.2.1 on 2019-07-30 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190730_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 20, 31, 56, 172973), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='image',
            name='text_tag',
            field=models.CharField(choices=[('SchoolLife', '大学生活'), ('Lab', '研究室'), ('Shop', '学食')], max_length=50, verbose_name='テキストタグ'),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 20, 31, 56, 172973), verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 20, 31, 56, 202896), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 20, 31, 56, 202896), verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='music',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 20, 31, 56, 202896), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='music',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 20, 31, 56, 202896), verbose_name='更新日時'),
        ),
    ]
